"""
Base PDF utilities and shared functions for all premium templates
"""

from reportlab.lib.colors import HexColor, white, black
from reportlab.lib.units import inch
from reportlab.platypus import Image, Paragraph
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
from pathlib import Path
import logging

logger = logging.getLogger(__name__)


class PDFColors:
    """Brand color palette"""
    NAVY = HexColor('#1F3A5F')
    BLUE = HexColor('#2563EB')
    LIGHT_BLUE = HexColor('#EFF6FF')
    GREY = HexColor('#64748B')
    LIGHT_GREY = HexColor('#F2F2F2')
    DARK_SLATE = HexColor('#1E293B')
    SLATE = HexColor('#334155')
    CHARCOAL = HexColor('#333333')
    BORDER_GREY = HexColor('#E2E8F0')
    STEEL_GREY = HexColor('#64748B')
    VERY_LIGHT_GREY = HexColor('#F8FAFC')
    WHITE = white
    BLACK = black


class PDFFonts:
    """Typography constants"""
    REGULAR = 'Helvetica'
    BOLD = 'Helvetica-Bold'
    OBLIQUE = 'Helvetica-Oblique'
    BOLD_OBLIQUE = 'Helvetica-BoldOblique'


def get_photo_image(photo_path, width, height):
    """
    Load and scale profile photo for PDF
    
    Args:
        photo_path: Path to photo file
        width: Desired width in inches
        height: Desired height in inches
    
    Returns:
        Image object or None if photo not available
    """
    if not photo_path:
        return None
    
    try:
        if Path(photo_path).exists():
            img = Image(photo_path, width=width, height=height)
            return img
    except Exception as e:
        logger.warning(f"Could not load photo: {e}")
    
    return None


def create_style(name, parent, **kwargs):
    """
    Create a custom paragraph style
    
    Args:
        name: Style name
        parent: Parent style
        **kwargs: Style properties
    
    Returns:
        ParagraphStyle object
    """
    return ParagraphStyle(name, parent=parent, **kwargs)


def format_phone(phone):
    """Format phone number for display"""
    if not phone:
        return ""
    return f"📱 {phone}"


def format_location(village_or_city, district, state, location=None):
    """Format location for display"""
    parts = []
    if village_or_city:
        parts.append(village_or_city)
    if district:
        parts.append(district)
    if state:
        parts.append(state)
    elif location:
        parts.append(location)
    
    if parts:
        return f"📍 {', '.join(parts)}"
    return ""


def format_languages(languages_spoken, languages=None):
    """Format languages for display"""
    lang_str = languages_spoken or languages
    if not lang_str:
        return ""
    
    lang_list = [l.strip() for l in lang_str.split(',') if l.strip()]
    if lang_list:
        return f"🗣️ {', '.join(lang_list[:3])}"  # First 3 languages
    return ""


def get_verified_badge_text(projects_completed, rating):
    """
    Generate verified worker badge text if qualified
    
    Args:
        projects_completed: Number of projects
        rating: Client rating
    
    Returns:
        Badge text or None
    """
    projects = projects_completed or 0
    rate = rating or 0
    
    if projects >= 20 and rate >= 4.0:
        return f"✓ VERIFIED WORKER | {projects}+ Projects | {rate:.1f}★ Rating"
    return None


def split_into_columns(items, num_columns=2):
    """
    Split a list of items into columns for table layout
    
    Args:
        items: List of items
        num_columns: Number of columns
    
    Returns:
        List of rows, each containing num_columns items
    """
    rows = []
    for i in range(0, len(items), num_columns):
        row = items[i:i + num_columns]
        # Pad with empty strings if needed
        while len(row) < num_columns:
            row.append('')
        rows.append(row)
    return rows


def add_footer_branding(canvas, doc):
    """
    Add subtle SkillLink branding to footer
    
    Args:
        canvas: ReportLab canvas
        doc: Document object
    """
    canvas.saveState()
    canvas.setFont(PDFFonts.REGULAR, 7)
    canvas.setFillColor(PDFColors.GREY)
    footer_text = "Generated by SkillLink"
    canvas.drawCentredString(doc.pagesize[0] / 2, 0.5 * inch, footer_text)
    canvas.restoreState()


def safe_get(data, *keys, default=None):
    """
    Safely get nested dictionary values
    
    Args:
        data: Dictionary
        *keys: Keys to traverse
        default: Default value if not found
    
    Returns:
        Value or default
    """
    for key in keys:
        if isinstance(data, dict):
            data = data.get(key)
            if data is None:
                return default
        else:
            return default
    return data if data is not None else default
